name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- git
- numpy
- conda-forge/label/ocl-icd-dev::ocl-icd=3.0.0.dev0
- pocl
- mako
- pybind11
- pip
- pip:
  - git+https://github.com/inducer/pytools.git@numpy-1.20-compat
